# Change these first
owner: dreamsquad-team # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Google
    url: https://www.google.com
    icon: https://www.google.com/favicon.ico

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: upptime.dreamsquad.com.br
  baseUrl: /upptime
  theme: night
  logoUrl: https://dreamsquad.com.br/wp-content/uploads/2024/06/LogoP.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/dreamsquad-team/upptime). No server required — just GitHub Actions, Issues, and Pages.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# workflowSchedule:
#   graphs: "0 0 * * *"
#   responseTime: "0 23 * * *"
#   staticSite: "0 1 * * *"
#   summary: "0 0 * * *"
#   updateTemplate: "0 0 * * *"
#   updates: "0 3 * * *"
#   uptime: "*/5 * * * *"

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
